src/Entity/Room.php
<?php

namespace App\Entity;

use App\Repository\RoomRepository;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RoomRepository::class)
 */
class Room
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $capacity;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isAvailable;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="rooms")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $update_at;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(?int $capacity): self
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getIsAvailable(): ?bool
    {
        return $this->isAvailable;
    }

    public function setIsAvailable(bool $isAvailable): self
    {
        $this->isAvailable = $isAvailable;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at->format('Y-m-d H:i:s');

        return $this;
    }

    public function getUpdateAt(): ?DateTimeInterface
    {
        return $this->update_at;
    }

    public function setUpdateAt(DateTimeInterface $update_at): self
    {
        $this->update_at = $update_at->format('Y-m-d H:i:s');

        return $this;
    }

}

src/Form/RoomType.php
<?php

namespace App\Form;

use App\Entity\Room;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class RoomType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'required' => true,
                /*'label' => true,*/
                'attr' => [
                    'placeholder' => 'Nom de la salle',
                    'class' => 'boostrap class',
                ]
            ])
            ->add('capacity', IntegerType::class)
            ->add('city', TextType::class)
            ->add('description', TextareaType::class, [
                'label' => false,
                'constraints' => [
                    new NotBlank([
                        'message' => 'Merci de mettre une description',
                    ]),
                    new Length([
                        'min'=>10,
                        'max'=>500,
                        'minMessage'=>'vous navez pas rentrez assez de caractere',
                        'maxMessage'=>'Veuillez réduire le NB de caracteres',
                    ])
                ],
                'attr' => [
                    'placeholder' => 'Ajouter une description',
                    'class' => 'boostrap class',
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Room::class,
            'translation_domain'=>'room_form',
        ]);
    }
}

src/Controller/RoomController.php
<?php

namespace App\Controller;

use App\Form\RoomType;
use App\Repository\RoomRepository;
use App\Entity\Room;
use DateTime;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

class RoomController extends AbstractController
{

    private $security;

    public function __construct(security $security)
    {
        $this->security = $security;
    }

    /**
     * @Route("/room", name="room")
     */
    public function index(RoomRepository $roomRepository): Response
    {
        $totalRooms = $roomRepository->findAll();
        $rooms = $roomRepository->findBy(['isAvailable' => 'true']);
        $count = count($rooms);
        $total = count($totalRooms);
        return $this->render('room/index.html.twig', [
            'controller_name' => 'RoomController',
            'rooms' => $rooms,
            'count' => $count,
            'total' => $total
        ]);
    }

    /**
     * @Route("/new", name="room.add", methods={"GET", "POST"})
     * @IsGranted("ROLE_USER")
     * @return Response
     *
     */
    public function new(Request $request): Response
    {
        $room = new Room();
        $room->setCreatedAt(new DateTime());
        $room->setUser($this->security->getUser());
        $form = $this->createForm(RoomType::class, $room);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($room);
            $entityManager->flush();

            $this->addFlash('success', 'la salle à bien été ajoutée');
            return $this->redirectToRoute('room');
        }

        return $this->render('room/new.html.twig', [
            'room' => $room,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/edit/{id}", name="room.edit", methods={"GET", "POST"})
     * @IsGranted ("ROLE_USER")
     */
    public function edit(Request $request, Room $room): Response
    {
        $form = $this->createForm(RoomType::class, $room);
        $form->handleRequest($request);
        $room->setUpdateAtAt(new DateTime());
        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('success', 'La modification de la salle a bien ete enregsitré');
            return $this->redirectToRoute('room');
        }
        return $this->render('room/edit.html.twig', [
            'room' => $room,
            'form' => $form->createView(),
        ]);

    }

    /**
     * @Route("/{id}", name="room.delete", methods={"DELETE"})
     * @IsGranted("ROLE_USER")
     * @return Response
     *
     */
    public function delete(Request $request, Room $room):Response
    {
        if ($this->isCsrfTokenValid('delete'.$room->getId(), $request->request->get('_token'))){
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($room);
            $entityManager->flush();

            $this->addFlash('success', 'La salle a bien été supprimée.');
        }
        return $this->redirectToRoute('room');
    }
}

templates/room/_form.html.twig
{{ form_start(form) }}
<div class="row">
    <div class="col-md-6">{{ form_row(form.name) }}</div>
    <div class="col-md-6">{{ form_row(form.description) }}</div>
</div>
<div class="row">
    <div class="col-md-6">{{ form_row(form.capacity) }}</div>
    <div class="col-md-6">{{ form_row(form.city) }}</div>
</div>

<button class="btn btn-primary mt-2">Valider</button>

{{ form_end(form) }}

templates/room/edit.html.twig
{% extends 'base.html.twig' %} {% block body %}

    {% block title %}  {% endblock %}


    <div class="container mt-5">
        <h1>Modifier une salle</h1>

        {{ include('room/_form.html.twig') }}


    </div>


{% endblock %}

templates/room/index.html.twig
{% extends 'base.html.twig' %} {% block body %}
    {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}
    <div class="container">

        <h1>Salles disponibles ({{ count }}/{{ total }})</h1>
        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
            <a type="button" class="btn btn-primary" href="{{ path('room.add') }}">Ajouter une salle</a>
        {% endif %}
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Capacity</th>
                <th scope="col">Category</th>
                <th scope="col">Disponibilité</th>
                {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                    <th scope="col">Actions</th>
                {% endif %}
                <th scope="col">Création</th>
                <th scope="col">Modification</th>
            </tr>
            </thead>
            <tbody>
            {% for room in rooms %}
                <tr>
                    <td>{{ room.id }}</td>
                    <td>{{ room.name }}</td>
                    <td>{{ room.city }}</td>
                    <td>{{ room.description | length > 100 ? room.description | slice(0,60) ~ '...' : room.description }}</td>
                    <td>{{ room.isAvailable }}</td>
                    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                        <td>
                            <a class="btn btn-primary" href="{{ path('room.edit', {id:room.id}) }}">Editer</a>
                            <form method="post" action="{{ path('room.delete', {id:room.id}) }}"
                                  style="display: inline-block" onsubmit="return confirm('confimer la suppression ?')">
                                <input type="hidden" name="_method" value="DELETE">
                                <input type="hidden" name="_token" value="{{ csrf_token('delete'~room.id) }}">
                                <button class="btn btn-danger">Supprimer</button>
                            </form>
                        </td>
                    {% endif %}
                    <td>{{ room.createdAt }}</td>
                    <td>{{ room.updateAt }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/room/new.html.twig
{% extends 'base.html.twig' %} {% block body %}

    {% block title %}  {% endblock %}


    <div class="container mt-5">
        <h1>Ajouter une salle</h1>

        {{ include('room/_form.html.twig') }}

    </div>


{% endblock %}